"""RuntimeManager: the trusted orchestration layer for sandbox lifecycles.

Depends only on `redstone.sandbox.SandboxProvider` and the neutral models --
never on Docker, subprocess, or any provider-specific type. RuntimeManager
itself is not a shell executor: every command a sandbox runs comes from
`SandboxCommand.resolve()`'s fixed table, never a string RuntimeManager built.

Two locks, two different jobs, matching the distinction already established in
redstone.agent.service:
  * `self._lock` guards the manager's own bookkeeping dicts (short critical
    sections only);
  * a per-workspace *admission* slot (`self._workspace_active`) enforces one
    active runtime per workspace, checked/set atomically under `self._lock`;
  * a per-runtime *operation* lock (`self._op_locks[runtime_id]`) serialises
    start/stop/restart/destroy on the SAME runtime, so concurrent calls
    cannot interleave and corrupt state.
"""

from __future__ import annotations

import logging
import hashlib
import os
import re
import threading
import time
from typing import Any, Callable

from ..domain.models import EventType, Framework, Runtime, RuntimeState, new_id
from ..events.bus import EventBus
from ..sandbox.commands import Operation, SandboxCommand
from ..sandbox.errors import RedstoneSandboxError, SandboxErrorCode
from ..sandbox.models import (
    InstallEgressPolicy,
    Mount,
    NetworkPolicy,
    PreviewUpstream,
    ResourceLimits,
    SandboxConfig,
    SandboxState,
)
from ..sandbox.provider import SandboxProvider
from ..workspace.manager import Workspace
from .errors import RedstoneRuntimeError, RuntimeErrorCode
from .models import TERMINAL_RUNTIME_STATES, transition

__all__ = ["RuntimeManager", "PROJECT_LABEL", "WORKSPACE_LABEL", "RUNTIME_LABEL", "PURPOSE_LABEL"]

_CONTAINER_PROJECT_PATH = "/workspace/project"
_DEV_SERVER_PORT = 5173


def _missing_rollup_native_package(logs: str) -> bool:
    """npm can exit zero after skipping Rollup's platform optional package.

    Rollup prints this diagnostic before Vite exits. A repeat install can
    fetch the missing package; other startup failures must not be retried.
    """
    return ("npm has a bug related to optional dependencies" in logs
            and "Cannot find module @rollup/rollup-linux-" in logs)


PROJECT_LABEL = "redstone.project_id"
WORKSPACE_LABEL = "redstone.workspace_id"
RUNTIME_LABEL = "redstone.runtime_id"
PURPOSE_LABEL = "redstone.purpose"
_SANDBOX_NAME_PREFIX = "redstone-"
# Ids are generated by Redstone (new_id / WorkspaceManager); anything else in
# an ownership label means the container was not labelled by this code.
_LABEL_VALUE = re.compile(r"^[A-Za-z0-9_-]{3,64}$")

_SANDBOX_TO_RUNTIME_ERROR = {
    SandboxErrorCode.CREATE_FAILED: RuntimeErrorCode.CREATE_FAILED,
    SandboxErrorCode.PROVIDER_UNAVAILABLE: RuntimeErrorCode.CREATE_FAILED,
    SandboxErrorCode.TIMEOUT: RuntimeErrorCode.TIMEOUT,
    SandboxErrorCode.DESTROY_FAILED: RuntimeErrorCode.DESTROY_FAILED,
}


class RuntimeManager:
    def __init__(
        self,
        provider: SandboxProvider,
        *,
        max_startup_seconds: float = 60.0,
        health_check_timeout: float = 5.0,
        stop_grace_seconds: float = 10.0,
        health_poll_interval: float = 1.0,
        resource_limits: ResourceLimits | None = None,
        egress_policy: InstallEgressPolicy | None = None,
        install_network_enabled: bool = True,
        event_bus: EventBus | None = None,
        logger: logging.Logger | None = None,
    ) -> None:
        self._provider = provider
        self._max_startup_seconds = max_startup_seconds
        self._health_check_timeout = health_check_timeout
        self._stop_grace_seconds = stop_grace_seconds
        self._health_poll_interval = health_poll_interval
        self._resource_limits = resource_limits or ResourceLimits()
        self._egress_policy = egress_policy or InstallEgressPolicy()
        self._install_network_enabled = install_network_enabled
        self._events = event_bus
        self._logger = logger

        self._lock = threading.Lock()
        self._runtimes: dict[str, Runtime] = {}
        self._workspace_active: dict[str, str] = {}   # workspace_id -> runtime_id
        self._op_locks: dict[str, threading.Lock] = {}
        self._expiry_timers: dict[str, threading.Timer] = {}
        self._prepared_manifests: dict[str, str] = {}
        self._preparation_ids: set[str] = set()
        self._preparation_errors: dict[str, str] = {}

    # ------------------------------------------------------------- lookup

    def _op_lock(self, runtime_id: str) -> threading.Lock:
        with self._lock:
            lock = self._op_locks.get(runtime_id)
            if lock is None:
                lock = threading.Lock()
                self._op_locks[runtime_id] = lock
            return lock

    def _get(self, runtime_id: str) -> Runtime:
        with self._lock:
            runtime = self._runtimes.get(runtime_id)
        if runtime is None:
            raise RedstoneRuntimeError(RuntimeErrorCode.NOT_FOUND)
        return runtime

    def _get_owned(self, runtime_id: str, project_id: str) -> Runtime:
        runtime = self._get(runtime_id)
        # Ownership is checked against server-side state recorded at create()
        # time, never against anything the caller merely asserts.
        if runtime.project_id != project_id:
            raise RedstoneRuntimeError(RuntimeErrorCode.NOT_OWNED)
        return runtime

    def _save(self, runtime: Runtime) -> Runtime:
        with self._lock:
            self._runtimes[runtime.id] = runtime
        return runtime

    def _release_slot(self, workspace_id: str, runtime_id: str) -> None:
        with self._lock:
            if self._workspace_active.get(workspace_id) == runtime_id:
                del self._workspace_active[workspace_id]

    def _cancel_expiry(self, runtime_id: str) -> None:
        with self._lock:
            timer = self._expiry_timers.pop(runtime_id, None)
        if timer is not None:
            timer.cancel()

    def _arm_expiry(self, runtime: Runtime) -> None:
        timer = threading.Timer(
            self._resource_limits.timeout_seconds,
            self._expire_runtime,
            args=(runtime.id, runtime.project_id),
        )
        timer.daemon = True
        with self._lock:
            self._expiry_timers[runtime.id] = timer
        timer.start()

    def _expire_runtime(self, runtime_id: str, project_id: str) -> None:
        try:
            current = self._get_owned(runtime_id, project_id)
            if current.state is not RuntimeState.RUNNING:
                return
            stopped = self.kill(runtime_id, project_id)
            if stopped.state is RuntimeState.KILLED:
                self._save(stopped.with_error(
                    RuntimeErrorCode.TIMEOUT.value, "The runtime exceeded its lifetime limit."
                ))
        except (RedstoneRuntimeError, RedstoneSandboxError):
            # Keep the workspace lease held on cleanup failure; destroy() can retry.
            return

    def _emit(self, event_type: EventType, runtime_id: str, *, project_id: str | None = None,
              **payload) -> None:
        if self._events is not None:
            self._events.publish(
                event_type, project_id=project_id,
                payload={"runtime_id": runtime_id, **payload},
            )
        if self._logger is not None:
            self._logger.info(f"runtime_event type={event_type.value} runtime_id={runtime_id}")

    @property
    def provider(self) -> SandboxProvider:
        """Read-only introspection (e.g. an honest health endpoint reporting
        whether the active provider actually provides isolation). Never used
        internally in place of self._provider -- this exists for callers
        outside the class."""
        return self._provider

    def get(self, runtime_id: str, project_id: str) -> Runtime:
        return self._get_owned(runtime_id, project_id)

    def preview_upstream(self, runtime_id: str, project_id: str) -> PreviewUpstream | None:
        """How the preview gateway reaches this runtime's server, if it is a
        RUNNING preview runtime on a provider that can isolate one."""
        runtime = self._get_owned(runtime_id, project_id)
        if runtime.state is not RuntimeState.RUNNING or not runtime.sandbox_id:
            return None
        lookup = getattr(self._provider, "preview_upstream", None)
        return lookup(runtime.sandbox_id) if lookup else None

    def list_for_project(self, project_id: str) -> tuple[Runtime, ...]:
        with self._lock:
            return tuple(r for r in self._runtimes.values()
                         if r.project_id == project_id and r.id not in self._preparation_ids)

    def dependency_status(self, workspace: Workspace, framework: Framework) -> dict[str, str]:
        """Safe, read-only readiness view; never starts an install."""
        if framework is not Framework.REACT_VITE_TS:
            return {"status": "ready"}
        with self._lock:
            active = self._workspace_active.get(workspace.id)
            preparing = active in self._preparation_ids
            last_error = self._preparation_errors.get(workspace.id)
        if preparing:
            return {"status": "preparing"}
        if not getattr(self._provider, "available", True):
            return {"status": "unavailable"}
        if self._dependencies_ready(workspace):
            return {"status": "ready"}
        if active is not None:
            return {"status": "busy"}
        if last_error is not None:
            return {"status": "failed", "error_code": last_error}
        return {"status": "needed"}

    def prepare_dependencies(
        self, project_id: str, workspace: Workspace, framework: Framework, *,
        is_cancelled: Callable[[], bool] | None = None,
    ) -> None:
        try:
            self._prepare_dependencies(project_id, workspace, framework,
                                       is_cancelled=is_cancelled)
        except RedstoneRuntimeError as exc:
            with self._lock:
                if exc.code in (RuntimeErrorCode.BUSY, RuntimeErrorCode.CANCELLED):
                    self._preparation_errors.pop(workspace.id, None)
                else:
                    self._preparation_errors[workspace.id] = exc.code.value
            raise
        else:
            with self._lock:
                self._preparation_errors.pop(workspace.id, None)

    def _prepare_dependencies(
        self, project_id: str, workspace: Workspace, framework: Framework, *,
        is_cancelled: Callable[[], bool] | None = None,
    ) -> None:
        """Prepare a project once per package manifest using the existing install sandbox.

        The runtime admission slot excludes concurrent preview starts and installs.
        A failed or cancelled install never marks the manifest ready. The cache is
        intentionally process-local; after a restart we recheck in the sandbox.
        """
        if framework is not Framework.REACT_VITE_TS:
            return
        manifest = workspace.project_root / "package.json"
        if not manifest.is_file() or manifest.is_symlink():
            raise RedstoneRuntimeError(RuntimeErrorCode.INVALID_REQUEST,
                                       safe_message="The project has no safe package manifest.")
        if manifest.stat().st_size > 1024 * 1024:
            raise RedstoneRuntimeError(RuntimeErrorCode.INVALID_REQUEST,
                                       safe_message="The package manifest is too large.")
        digest = hashlib.sha256(manifest.read_bytes()).hexdigest()
        with self._lock:
            ready = (self._prepared_manifests.get(workspace.id) == digest
                     and (workspace.project_root / "node_modules").is_dir()
                     and not (workspace.project_root / "node_modules").is_symlink())
        if ready:
            return
        if is_cancelled is not None and is_cancelled():
            raise RedstoneRuntimeError(RuntimeErrorCode.CANCELLED)

        runtime = self.create(project_id, workspace, framework, _preparation=True)
        with self._lock:
            self._prepared_manifests.pop(workspace.id, None)
        try:
            with self._op_lock(runtime.id):
                try:
                    self._run_install(runtime, workspace, is_cancelled=is_cancelled)
                except RedstoneSandboxError as exc:
                    code = _SANDBOX_TO_RUNTIME_ERROR.get(exc.code, RuntimeErrorCode.START_FAILED)
                    raise RedstoneRuntimeError(code, safe_message=exc.safe_message) from exc
            if is_cancelled is not None and is_cancelled():
                raise RedstoneRuntimeError(RuntimeErrorCode.CANCELLED)
        finally:
            # If cleanup fails, destroy() retains the workspace slot so no
            # second install can race a potentially live sandbox.
            try:
                self.destroy(runtime.id, project_id)
            except RedstoneRuntimeError:
                with self._lock:
                    self._preparation_ids.discard(runtime.id)
                raise
            with self._lock:
                self._runtimes.pop(runtime.id, None)
                self._op_locks.pop(runtime.id, None)
                self._preparation_ids.discard(runtime.id)
        if hashlib.sha256(manifest.read_bytes()).hexdigest() != digest:
            raise RedstoneRuntimeError(RuntimeErrorCode.INVALID_REQUEST,
                                       safe_message="The package manifest changed during preparation.")
        with self._lock:
            self._prepared_manifests[workspace.id] = digest

    # -------------------------------------------------------------- create

    def create(self, project_id: str, workspace: Workspace, framework: Framework, *,
               _preparation: bool = False) -> Runtime:
        if not getattr(self._provider, "available", True):
            raise RedstoneRuntimeError(
                RuntimeErrorCode.CREATE_FAILED,
                safe_message="The isolated sandbox provider is unavailable.",
            )
        with self._lock:
            existing = self._workspace_active.get(workspace.id)
            if existing is not None:
                raise RedstoneRuntimeError(RuntimeErrorCode.BUSY)
            runtime = Runtime(
                id=new_id("rt"), project_id=project_id, workspace_id=workspace.id,
                framework=framework,
            )
            self._runtimes[runtime.id] = runtime
            self._workspace_active[workspace.id] = runtime.id
            if _preparation:
                self._preparation_ids.add(runtime.id)

        self._emit(EventType.RUNTIME_CREATED, runtime.id, project_id=project_id)
        return runtime

    # --------------------------------------------------------------- start

    def start(self, runtime_id: str, project_id: str, workspace: Workspace, *,
              preview: bool = False) -> Runtime:
        """`preview=True` runs the dev server under NetworkPolicy.PREVIEW so
        Redstone's preview relay can reach it; the default keeps the Phase 5
        `--network none` server."""
        with self._op_lock(runtime_id):
            runtime = self._get_owned(runtime_id, project_id)

            if runtime.state is RuntimeState.RUNNING:
                return runtime   # idempotent: starting a running runtime is a no-op

            runtime = self._save(transition(runtime, RuntimeState.STARTING))
            self._emit(EventType.RUNTIME_STARTING, runtime.id)

            try:
                needs_dependencies = self._needs_dependencies(workspace)
                manifest_before = self._manifest_digest(workspace) if needs_dependencies else None
                if needs_dependencies and not self._dependencies_ready(workspace):
                    self._run_install(runtime, workspace)

                for attempt in range(2):
                    sandbox_id = self._start_dev_server(runtime, workspace, preview)
                    runtime = self._save(runtime.with_sandbox(sandbox_id, self._provider.name))

                    if self._wait_until_healthy(sandbox_id):
                        break
                    exceeded = self._provider.status(sandbox_id).resource_limit_exceeded
                    retry_install = False
                    if attempt == 0 and needs_dependencies and not exceeded:
                        try:
                            logs = self._provider.logs(sandbox_id, max_bytes=4096)
                        except RedstoneSandboxError:
                            logs = ""
                        retry_install = _missing_rollup_native_package(logs)
                    self._safe_teardown(sandbox_id)
                    runtime = self._save(self._get(runtime.id).with_sandbox(None, None))
                    if exceeded:
                        raise RedstoneRuntimeError(
                            RuntimeErrorCode.RESOURCE_LIMIT,
                            safe_message=f"The runtime exceeded the sandbox '{exceeded}' limit.",
                        )
                    if retry_install:
                        self._run_install(runtime, workspace)
                        continue
                    raise RedstoneRuntimeError(RuntimeErrorCode.HEALTHCHECK_FAILED)

            except RedstoneRuntimeError as exc:
                runtime = self._get(runtime.id)
                runtime = self._save(
                    transition(runtime, RuntimeState.FAILED).with_error(exc.code.value, exc.safe_message)
                )
                if runtime.sandbox_id is None:
                    self._release_slot(runtime.workspace_id, runtime.id)
                self._emit(EventType.RUNTIME_FAILED, runtime.id, error_code=exc.code.value)
                raise
            except RedstoneSandboxError as exc:
                runtime = self._get(runtime.id)
                code = _SANDBOX_TO_RUNTIME_ERROR.get(exc.code, RuntimeErrorCode.START_FAILED)
                wrapped = RedstoneRuntimeError(code, safe_message=exc.safe_message,
                                               internal=exc.internal)
                runtime = self._save(
                    transition(runtime, RuntimeState.FAILED).with_error(code.value, exc.safe_message)
                )
                if runtime.sandbox_id is None:
                    self._release_slot(runtime.workspace_id, runtime.id)
                self._emit(EventType.RUNTIME_FAILED, runtime.id, error_code=code.value)
                raise wrapped from exc

            runtime = self._save(transition(self._get(runtime.id), RuntimeState.RUNNING))
            if manifest_before is not None and self._manifest_digest(workspace) == manifest_before:
                with self._lock:
                    self._prepared_manifests[workspace.id] = manifest_before
                    self._preparation_errors.pop(workspace.id, None)
            self._arm_expiry(runtime)
            self._emit(EventType.RUNTIME_STARTED, runtime.id)
            return runtime

    def _needs_dependencies(self, workspace: Workspace) -> bool:
        return (workspace.project_root / "package.json").is_file()

    @staticmethod
    def _manifest_digest(workspace: Workspace) -> str | None:
        manifest = workspace.project_root / "package.json"
        try:
            if (not manifest.is_file() or manifest.is_symlink()
                    or manifest.stat().st_size > 1024 * 1024):
                return None
            return hashlib.sha256(manifest.read_bytes()).hexdigest()
        except OSError:
            return None

    def _dependencies_ready(self, workspace: Workspace) -> bool:
        modules = workspace.project_root / "node_modules"
        with self._lock:
            prepared = self._prepared_manifests.get(workspace.id)
        return bool(prepared and modules.is_dir() and not modules.is_symlink()
                    and self._manifest_digest(workspace) == prepared)

    def _run_install(self, runtime: Runtime, workspace: Workspace, *,
                     is_cancelled: Callable[[], bool] | None = None) -> None:
        command = SandboxCommand(Operation.INSTALL_DEPENDENCIES, runtime.framework)
        config = self._build_config(
            runtime, workspace, command,
            # With install networking disabled the install gets NO network --
            # never a wider one.
            network_policy=(NetworkPolicy.INSTALL_ONLY
                            if command.needs_network and self._install_network_enabled
                            else NetworkPolicy.DENY),
            timeout_seconds=command.max_timeout_seconds,
        )
        sandbox_id = self._provider.create(config)
        self._save(self._get(runtime.id).with_sandbox(sandbox_id, self._provider.name))
        cancelled = threading.Event()
        finished = threading.Event()
        watcher: threading.Thread | None = None
        try:
            if is_cancelled is not None and is_cancelled():
                cancelled.set()
                raise RedstoneRuntimeError(RuntimeErrorCode.CANCELLED)
            self._provider.start(sandbox_id)
            if is_cancelled is not None:
                def _watch_cancel() -> None:
                    while not finished.wait(0.1):
                        if is_cancelled():
                            cancelled.set()
                            try:
                                self._provider.kill(sandbox_id)
                            except RedstoneSandboxError:
                                pass  # destroy below still owns cleanup
                            return
                watcher = threading.Thread(target=_watch_cancel, daemon=True)
                watcher.start()
            result = self._provider.wait(sandbox_id, timeout=command.max_timeout_seconds)
        except RedstoneSandboxError as exc:
            if cancelled.is_set() or (is_cancelled is not None and is_cancelled()):
                raise RedstoneRuntimeError(RuntimeErrorCode.CANCELLED) from exc
            raise
        finally:
            finished.set()
            if watcher is not None:
                watcher.join(timeout=1)
            self._provider.destroy(sandbox_id)
            self._save(self._get(runtime.id).with_sandbox(None, None))

        if cancelled.is_set() or (is_cancelled is not None and is_cancelled()):
            raise RedstoneRuntimeError(RuntimeErrorCode.CANCELLED)

        diagnostics = (result.stdout[-1000:] + result.stderr[-1000:])
        if result.resource_limit_exceeded:
            raise RedstoneRuntimeError(
                RuntimeErrorCode.RESOURCE_LIMIT,
                safe_message=(
                    "Dependency installation exceeded the sandbox "
                    f"'{result.resource_limit_exceeded}' limit and was stopped."
                ),
                internal=diagnostics,
            )
        if result.timed_out:
            raise RedstoneRuntimeError(
                RuntimeErrorCode.TIMEOUT,
                safe_message="Dependency installation timed out.",
                internal=diagnostics,
            )
        if not result.ok:
            raise RedstoneRuntimeError(
                RuntimeErrorCode.START_FAILED,
                safe_message="Dependency installation failed.",
                internal=diagnostics,
            )

    def _start_dev_server(self, runtime: Runtime, workspace: Workspace, preview: bool = False) -> str:
        operation = Operation.START_PREVIEW_SERVER if preview else Operation.START_DEV_SERVER
        command = SandboxCommand(operation, runtime.framework)
        config = self._build_config(
            runtime, workspace, command,
            network_policy=NetworkPolicy.PREVIEW if preview else NetworkPolicy.DENY,
            timeout_seconds=self._resource_limits.timeout_seconds,
        )
        sandbox_id = self._provider.create(config)
        self._save(self._get(runtime.id).with_sandbox(sandbox_id, self._provider.name))
        try:
            self._provider.start(sandbox_id)
        except Exception:
            self._provider.destroy(sandbox_id)
            self._save(self._get(runtime.id).with_sandbox(None, None))
            raise
        return sandbox_id

    def _build_config(
        self, runtime: Runtime, workspace: Workspace, command: SandboxCommand, *,
        network_policy: NetworkPolicy, timeout_seconds: float,
    ) -> SandboxConfig:
        limits = ResourceLimits(
            cpu_cores=self._resource_limits.cpu_cores,
            memory_mb=self._resource_limits.memory_mb,
            pids=self._resource_limits.pids,
            timeout_seconds=timeout_seconds,
            output_bytes=self._resource_limits.output_bytes,
            storage_mb=self._resource_limits.storage_mb,
        )
        environment = {"NODE_ENV": "development", "PORT": str(_DEV_SERVER_PORT)}
        # Docker Desktop's Windows bind mounts can miss host-side file events.
        # Poll only live previews there so edits made by the agent are visible
        # without changing a project's own Vite configuration.
        if os.name == "nt" and command.operation is Operation.START_PREVIEW_SERVER:
            environment["CHOKIDAR_USEPOLLING"] = "true"
            environment["CHOKIDAR_INTERVAL"] = "500"
        return SandboxConfig(
            mounts=(Mount(workspace.project_root, _CONTAINER_PROJECT_PATH, read_only=False),),
            working_dir=_CONTAINER_PROJECT_PATH,
            command=command,
            # The complete environment. Nothing from AIConfig, nothing from
            # os.environ -- RuntimeManager has no reference to either.
            environment=environment,
            network_policy=network_policy,
            resource_limits=limits,
            egress=self._egress_policy,
            # Opaque ids only. These survive a Redstone restart on the
            # container itself, which is what reconcile_orphaned_containers()
            # reads back.
            labels={
                PROJECT_LABEL: runtime.project_id,
                WORKSPACE_LABEL: runtime.workspace_id,
                RUNTIME_LABEL: runtime.id,
                PURPOSE_LABEL: command.operation.value,
            },
        )

    def _wait_until_healthy(self, sandbox_id: str) -> bool:
        deadline = time.monotonic() + self._max_startup_seconds
        probe = ("wget", "-T", "2", "-q", "-O", "-", f"http://127.0.0.1:{_DEV_SERVER_PORT}")

        while time.monotonic() < deadline:
            status = self._provider.status(sandbox_id)
            if status.state not in (SandboxState.RUNNING, SandboxState.CREATED, SandboxState.STARTING):
                return False   # crashed during startup

            result = self._provider.exec_in(sandbox_id, probe, timeout=self._health_check_timeout)
            if result.exit_code == 0:
                return True
            time.sleep(self._health_poll_interval)

        return False

    def _safe_teardown(self, sandbox_id: str) -> None:
        try:
            self._provider.kill(sandbox_id)
        finally:
            self._provider.destroy(sandbox_id)

    # ---------------------------------------------------------- health check

    def health_check(self, runtime_id: str, project_id: str) -> bool:
        """On-demand crash detection for an already-RUNNING runtime.

        Distinguishes "process exists" (sandbox state) from "server
        responding" (the probe) -- a container can be alive with a hung
        server, which this correctly reports as unhealthy.
        """
        runtime = self._get_owned(runtime_id, project_id)
        if runtime.state is not RuntimeState.RUNNING or runtime.sandbox_id is None:
            return False

        status = self._provider.status(runtime.sandbox_id)
        self._emit(EventType.RUNTIME_HEALTH_CHECK, runtime.id, sandbox_state=status.state.value)

        if status.state is not SandboxState.RUNNING:
            self._mark_crashed(runtime)
            return False

        probe = ("wget", "-T", "2", "-q", "-O", "-", f"http://127.0.0.1:{_DEV_SERVER_PORT}")
        result = self._provider.exec_in(runtime.sandbox_id, probe, timeout=self._health_check_timeout)
        if result.exit_code != 0:
            self._mark_crashed(runtime)
            return False
        return True

    def _mark_crashed(self, runtime: Runtime) -> None:
        with self._op_lock(runtime.id):
            current = self._get(runtime.id)
            if current.state in TERMINAL_RUNTIME_STATES:
                return   # already handled by a concurrent stop/destroy
            diagnostics = ""
            exceeded = None
            if current.sandbox_id:
                try:
                    diagnostics = self._provider.logs(current.sandbox_id, max_bytes=4096)
                    exceeded = self._provider.status(current.sandbox_id).resource_limit_exceeded
                except RedstoneSandboxError:
                    pass
            if exceeded:
                code = RuntimeErrorCode.RESOURCE_LIMIT
                message = f"The runtime exceeded the sandbox '{exceeded}' limit and was stopped."
            else:
                code = RuntimeErrorCode.HEALTHCHECK_FAILED
                message = "The runtime process is no longer responding."
            if current.sandbox_id:
                try:
                    self._safe_teardown(current.sandbox_id)
                except RedstoneSandboxError:
                    self._save(
                        transition(current, RuntimeState.FAILED).with_error(
                            RuntimeErrorCode.DESTROY_FAILED.value,
                            "The failed runtime could not be cleaned up.",
                        )
                    )
                    return  # keep workspace lease until destroy() succeeds
            updated = self._save(
                transition(current, RuntimeState.FAILED).with_error(code.value, message)
            )
            self._cancel_expiry(updated.id)
            self._release_slot(updated.workspace_id, updated.id)
            self._emit(EventType.RUNTIME_CRASHED, updated.id, diagnostics_bytes=len(diagnostics))

    # ----------------------------------------------------------------- logs

    def logs(self, runtime_id: str, project_id: str, max_bytes: int = 64 * 1024) -> str:
        runtime = self._get_owned(runtime_id, project_id)
        if runtime.sandbox_id is None:
            return ""
        return self._provider.logs(runtime.sandbox_id, max_bytes)

    # ----------------------------------------------------------------- stop

    def stop(self, runtime_id: str, project_id: str) -> Runtime:
        with self._op_lock(runtime_id):
            runtime = self._get_owned(runtime_id, project_id)
            if runtime.state in TERMINAL_RUNTIME_STATES:
                return runtime   # idempotent

            self._emit(EventType.RUNTIME_STOPPING, runtime.id)

            if runtime.sandbox_id:
                try:
                    self._provider.stop(runtime.sandbox_id, timeout=self._stop_grace_seconds)
                    self._provider.destroy(runtime.sandbox_id)
                except RedstoneSandboxError as exc:
                    raise RedstoneRuntimeError(RuntimeErrorCode.STOP_FAILED,
                                               safe_message=exc.safe_message) from exc

            runtime = self._save(transition(runtime, RuntimeState.STOPPING))
            runtime = self._save(transition(runtime, RuntimeState.STOPPED))
            self._cancel_expiry(runtime.id)
            self._release_slot(runtime.workspace_id, runtime.id)
            self._emit(EventType.RUNTIME_STOPPED, runtime.id)
            return runtime

    # ----------------------------------------------------------------- kill

    def kill(self, runtime_id: str, project_id: str) -> Runtime:
        with self._op_lock(runtime_id):
            runtime = self._get_owned(runtime_id, project_id)
            if runtime.state in TERMINAL_RUNTIME_STATES:
                return runtime   # idempotent

            if runtime.sandbox_id:
                self._provider.kill(runtime.sandbox_id)
                self._provider.destroy(runtime.sandbox_id)

            runtime = self._save(transition(runtime, RuntimeState.KILLED))
            self._cancel_expiry(runtime.id)
            self._release_slot(runtime.workspace_id, runtime.id)
            self._emit(EventType.RUNTIME_KILLED, runtime.id)
            return runtime

    # -------------------------------------------------------------- destroy

    def destroy(self, runtime_id: str, project_id: str | None = None) -> None:
        with self._op_lock(runtime_id):
            with self._lock:
                runtime = self._runtimes.get(runtime_id)
            if runtime is None:
                return   # idempotent: destroying an unknown id is a no-op

            if project_id is not None and runtime.project_id != project_id:
                raise RedstoneRuntimeError(RuntimeErrorCode.NOT_OWNED)

            if runtime.state is RuntimeState.DESTROYED:
                return   # idempotent

            if runtime.sandbox_id:
                try:
                    self._provider.destroy(runtime.sandbox_id)
                except RedstoneSandboxError as exc:
                    raise RedstoneRuntimeError(RuntimeErrorCode.DESTROY_FAILED,
                                               safe_message=exc.safe_message) from exc

            runtime = self._save(transition(runtime, RuntimeState.DESTROYED))
            self._cancel_expiry(runtime.id)
            self._release_slot(runtime.workspace_id, runtime.id)
            self._emit(EventType.RUNTIME_DESTROYED, runtime.id)

    # ------------------------------------------------------------- restart

    def restart(self, runtime_id: str, project_id: str, workspace: Workspace, *,
                preview: bool = False) -> Runtime:
        """Destroy the current generation and start a fresh one for the same
        project/workspace. The runtime_id changes -- see docs/redstone/
        RUNTIME.md "one active runtime + historical generations" for why:
        it avoids ever needing to re-enter a terminal state, which would
        otherwise require a special-cased hole in the state machine.
        """
        old = self._get_owned(runtime_id, project_id)
        framework = old.framework

        self.destroy(runtime_id, project_id)
        # destroy() released the workspace slot; verify before proceeding so
        # a concurrent create() cannot have raced in ahead of us.
        with self._lock:
            still_held = self._workspace_active.get(workspace.id)
        if still_held not in (None, runtime_id):
            raise RedstoneRuntimeError(RuntimeErrorCode.BUSY)

        new_runtime = self.create(project_id, workspace, framework)
        try:
            return self.start(new_runtime.id, project_id, workspace, preview=preview)
        except RedstoneRuntimeError:
            # start() already marked new_runtime FAILED and released its
            # slot; nothing is left ambiguously "running".
            raise

    # -------------------------------------------------------- reconciliation

    def reconcile(self) -> int:
        """Detect and clean up runtimes whose sandbox no longer matches our
        recorded state -- a process that crashed between health checks, or
        (for providers that support it) a container left over from a prior
        Redstone process that never got a chance to call destroy(). Returns
        the number of runtimes corrected."""
        corrected = 0
        with self._lock:
            snapshot = [r for r in self._runtimes.values()
                        if r.id not in self._preparation_ids]

        for runtime in snapshot:
            if runtime.state in TERMINAL_RUNTIME_STATES or runtime.sandbox_id is None:
                continue
            status = self._provider.status(runtime.sandbox_id)
            if status.state not in (SandboxState.RUNNING, SandboxState.STARTING):
                self._mark_crashed(runtime)
                corrected += 1

        return corrected

    def reconcile_orphaned_containers(self) -> dict:
        """Recover from a Redstone process restart.

        `reconcile()` above only sees runtimes this process still holds in
        memory. A container created by a previous Redstone process survives
        that process's death, but its `Runtime` record does not. This method
        asks the provider directly (`list_managed()` -- Docker labels, not
        memory) for every Redstone-owned sandbox and destroys each one that
        does not belong to a runtime this process is actively tracking.

        Policy: destroy, never adopt. A restarted process cannot know whether
        a surviving container finished its install, passed its health check,
        or is serving the files it should be; re-adopting it as RUNNING would
        mean trusting state nobody verified. Destroying it is always safe --
        the caller simply starts the project again -- and it guarantees no
        duplicate runtime can exist alongside a fresh one for the same
        workspace.

        Never touches anything without the provider's ownership marker
        (filtered by the Docker CLI itself) and additionally skips anything
        whose name lacks the provider's `redstone-` prefix.
        """
        with self._lock:
            live_runtime_ids = {
                r.id for r in self._runtimes.values() if r.state not in TERMINAL_RUNTIME_STATES
            }
            live_sandbox_ids = {
                r.sandbox_id for r in self._runtimes.values()
                if r.sandbox_id and r.state not in TERMINAL_RUNTIME_STATES
            }

        report: dict[str, Any] = {"destroyed": [], "malformed": 0, "kept": 0,
                                  "skipped_unrecognised": 0, "failed": []}
        for entry in self._provider.list_managed():
            sandbox_id = entry.get("sandbox_id") or ""
            labels = entry.get("labels") or {}
            if not sandbox_id.startswith(_SANDBOX_NAME_PREFIX):
                report["skipped_unrecognised"] += 1
                continue

            runtime_id = labels.get(RUNTIME_LABEL, "")
            well_formed = all(
                _LABEL_VALUE.match(labels.get(key, "") or "")
                for key in (PROJECT_LABEL, WORKSPACE_LABEL, RUNTIME_LABEL)
            )
            if well_formed and (runtime_id in live_runtime_ids or sandbox_id in live_sandbox_ids):
                report["kept"] += 1
                continue
            if not well_formed:
                report["malformed"] += 1

            try:
                self._provider.destroy(sandbox_id)
                report["destroyed"].append(sandbox_id)
            except RedstoneSandboxError:
                report["failed"].append(sandbox_id)

        if self._logger is not None:
            self._logger.info(
                "runtime_orphan_reconcile destroyed=%d malformed=%d kept=%d failed=%d",
                len(report["destroyed"]), report["malformed"], report["kept"],
                len(report["failed"]),
            )
        return report
